---
abstract: 'User role-based authorization action class'
author:
  - 'David P.C. Wollmann <converter42@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.50
distribution_type: module
generated_by: 'Module::Install version 0.81'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Action-Role-ACL
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Runtime: 0
  MRO::Compat: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
